Repository stamford-syntax-club/stamfordcenter-backend, pull requests merged in 2023-08, with the labels that each got.

#3 fix: add region
  src/utils/s3connection.ts
Labels: bug

#4 revert region
  src/utils/s3connection.ts
Labels: bug

#5 add gitops pipeline
  .github/workflows/dev.yaml
Labels: enhancement

#7 [skip actions] add readme
  LICENSE
  README.md
Labels: documentation, enhancement
